development:
  sessions:
    default:
      database: academical_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: academical_test
      hosts:
        - localhost:27017
