production:
  clients:
    default:
      uri: <%= ENV['MONGO_URI_PROD'] %>
      options:
        min_pool_size: 25
        max_pool_size: 100
        read:
          mode: :primary_preferred
staging:
  clients:
    default:
      uri: <%= ENV['MONGO_URI_STAGING'] %>
      options:
        min_pool_size: 25
        max_pool_size: 50
        connect_timeout: 15
development:
  clients:
    default:
      database: academical_dev
      hosts:
        - localhost:27017
      options:
        pool_size: 50
        pool_timeout: 15
        retry_interval: 1
        timeout: 60
        max_retries: 20
        refresh_interval: 30
test:
  clients:
    default:
      database: academical_test
      hosts:
        - localhost:27017
