production:
  sessions:
    default:
      uri: <%= ENV['MONGO_URI_PROD'] %>
      options:
        pool_size: 50

development:
  sessions:
    default:
      uri: <%= ENV['MONGO_URI_STAGING'] %>
      options:
        pool_size: 50
test:
  sessions:
    default:
      database: academical_test
      hosts:
        - localhost:27017
