development:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        pool_size: 50
test:
  sessions:
    default:
      database: academical_test
      hosts:
        - localhost:27017
